name: Terraform CI/CD

on:
  push:
    branch: main    
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-lastest   
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -backend false   

      - name: Terraform Validate
        run: terraform validat         

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Terraform Apply
        run: terraform apply -auto-approv    
